### PR TITLE
Pin pytorch version and remove unnecerray dependencies

### PR DESCRIPTION
**Pull request by AntoinePrv**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Related to https://github.com/conda-forge/pytorch_scatter-feedstock/pull/24

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@conda-forge-admin, please rerender

**Comment by AntoinePrv** [comment]
I'm not able to figure this error:
```
  .../ld: cannot find -lc10_cuda
  .../ld: cannot find -ltorch_cuda
  collect2: error: ld returned 1 exit status
```
Seems to be the same one as in the `main` branch.

**Comment by hadim** [comment]
Friendly ping here about pinning.

**Comment by hmaarrfk** [comment]
@hadim i'm sorry to say that you will have to revive this refresh yourself before you can pin somebody with powers to merge. This is quite old in "pytorch months" and I wouldn't recommend building against pytorch 1.8 on conda-forge.

If you absolutely need pytorch 1.8, you may make a PR against pytorch-cpu-feedstock building it, and I can make a branch if you want to maintain it, but I suspect it won't be easy.

it seems there has been a newer version of this package. Try starting from there?

**Comment by hadim** [comment]
I don't need pytorch 1.8 and I am fine working with newer versions. I am having some trouble with some `pytorch_xxxx` libs (as you have noticed probably). I was simply pinging here to see what was the status of the pinning. But it looks like you guys did the work already.

**Comment by hmaarrfk** [comment]
If you start a merge request, i'm happy to edit the pinnings if you ping me, I just don't want to piggy back on a stalled PR without the author's permission.

**Comment by hmaarrfk** [comment]
(it also has some conflicts)

**Comment by hadim** [comment]
I totally understand. Thanks @hmaarrfk .

**Comment by AntoinePrv** [comment]
Hello, I haven't had time to look at what has changed with the new Pytorch pinning but I'm sure it will solve this.
Anyways, as mentioned, this is old and full of conflicts, so I would probably start fresh if I still find some issues.

**Pull request closed without merging**
